/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SparkRecordBlock = {
  _type: "sparkRecordBlock";
  date: string;
  when?: LocaleString;
  label?: LocaleString;
  paragraphs?: Array<{
    _key: string;
  } & LocaleText>;
  sources?: Array<{
    label?: LocaleString;
    href?: string;
    _type: "sparkBlockSource";
    _key: string;
  }>;
};

export type SparkChoiceDecision = {
  _type: "sparkChoiceDecision";
  date: string;
  when?: LocaleString;
  label?: LocaleString;
  title?: LocaleString;
  paragraphs?: Array<{
    _key: string;
  } & LocaleText>;
  options?: Array<{
    _key: string;
  } & SparkChoiceOption>;
  record: string;
  reveal?: Array<{
    _key: string;
  } & LocaleText>;
  sources?: Array<{
    label?: LocaleString;
    href?: string;
    _type: "sparkBlockSource";
    _key: string;
  }>;
};

export type SparkRulerTick = {
  _type: "sparkRulerTick";
  date: string;
  label?: LocaleString;
  caption?: LocaleString;
};

export type SparkChoiceOption = {
  _type: "sparkChoiceOption";
  key: string;
  text?: LocaleText;
};

export type SparkSource = {
  _type: "sparkSource";
  n: number;
  links?: Array<{
    label?: LocaleString;
    href?: string;
    _type: "sparkSourceLink";
    _key: string;
  }>;
};

export type SparkFinalOption = {
  _type: "sparkFinalOption";
  text?: LocaleText;
  service: "zero-to-live" | "product-strategy" | "embedded-finance" | "expansion-gtm";
  serviceName?: LocaleString;
  heading?: LocaleString;
  body?: LocaleText;
};

export type SparkChapter = {
  _type: "sparkChapter";
  id: string;
  label?: LocaleString;
  title?: LocaleString;
  lead?: LocaleText;
  paragraphs?: Array<{
    _key: string;
  } & LocaleText>;
  card?: SparkStoryCard;
  decision?: SparkDecision;
};

export type SparkDecision = {
  _type: "sparkDecision";
  label?: LocaleString;
  question?: LocaleText;
  options?: Array<{
    _key: string;
  } & SparkDecisionOption>;
  didLabel?: LocaleString;
  didTitle?: LocaleText;
  didBody?: Array<{
    _key: string;
  } & LocaleText>;
  note?: LocaleText;
  services?: Array<{
    _key: string;
  } & SparkServiceTag>;
};

export type SparkDecisionOption = {
  _type: "sparkDecisionOption";
  key: string;
  text?: LocaleText;
  answer?: LocaleText;
};

export type SparkServiceTag = {
  _type: "sparkServiceTag";
  name?: LocaleString;
  service: "zero-to-live" | "product-strategy" | "embedded-finance" | "expansion-gtm";
};

export type SparkStoryCard = {
  _type: "sparkStoryCard";
  mode: "draft" | "live" | "flipped" | "closed";
  day: string;
  state?: LocaleString;
  caption?: LocaleString;
  barTitle?: LocaleString;
  progress?: number;
  barDay?: LocaleString;
};

export type SparkEpisode = {
  _id: string;
  _type: "sparkEpisode";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  format: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sparkFormat";
  };
  number: number;
  slug?: LocaleSlug;
  seo?: Seo;
  subject?: LocaleString;
  layout?: "story" | "decisions";
  city?: string;
  country?: string;
  launchDate?: string;
  launchPrecision?: "day" | "month";
  durationLabel?: LocaleString;
  closureDate?: string;
  hook?: LocaleText;
  status: "published" | "coming" | "draft";
  cardLine?: LocaleText;
  publishedAt?: string;
  lastCheckedAt?: string;
  previewLive?: boolean;
  hero?: {
    label?: LocaleString;
    title?: LocaleText;
    sub?: LocaleText;
    invite?: LocaleText;
    startLabel?: LocaleString;
    cardDay?: string;
    cardState?: LocaleString;
    figure?: string;
    figureLabel?: LocaleString;
  };
  dayClock?: {
    label?: LocaleString;
    ofLabel?: LocaleString;
  };
  chapters?: Array<{
    _key: string;
  } & SparkChapter>;
  interlude?: {
    afterChapter?: string;
    text?: LocaleText;
    card?: SparkStoryCard;
  };
  lessons?: Array<{
    heading?: LocaleString;
    body?: LocaleText;
    _type: "sparkLesson";
    _key: string;
  }>;
  note?: {
    label?: LocaleString;
    paragraphs?: Array<{
      _key: string;
    } & LocaleText>;
  };
  lastDay?: {
    label?: LocaleString;
    text?: LocaleText;
  };
  finalQuestion?: {
    label?: LocaleString;
    title?: LocaleText;
    lead?: LocaleText;
    ctaLabel?: LocaleString;
    options?: Array<{
      _key: string;
    } & SparkFinalOption>;
  };
  next?: {
    number?: string;
    name?: LocaleString;
    line?: LocaleText;
  };
  sourcesLabel?: LocaleString;
  sources?: Array<{
    _key: string;
  } & SparkSource>;
  correctionLine?: LocaleText;
  closeHeading?: LocaleString;
  opening?: {
    label?: LocaleString;
    meta?: LocaleString;
    figure?: string;
    figureLabel?: LocaleString;
  };
  ruler?: {
    ticks?: Array<{
      _key: string;
    } & SparkRulerTick>;
    after?: LocaleText;
  };
  standfirst?: LocaleText;
  provenance?: LocaleString;
  clock?: {
    rangeLabel?: LocaleString;
    start: string;
    end: string;
  };
  intro?: LocaleText;
  labels?: {
    ask?: LocaleString;
    skip?: LocaleString;
    match?: LocaleString;
    noMatch?: LocaleString;
    revealLabel?: LocaleString;
    sourcesLabel?: LocaleString;
  };
  decisions?: Array<{
    _key: string;
  } & SparkChoiceDecision>;
  records?: Array<{
    _key: string;
  } & SparkRecordBlock>;
  twist?: {
    date: string;
    when?: LocaleString;
    label?: LocaleString;
    paragraphs?: Array<{
      _key: string;
    } & LocaleText>;
    question?: LocaleText;
    options?: Array<{
      _key: string;
    } & SparkChoiceOption>;
    freeKey?: string;
    freeLabel?: LocaleString;
    freePlaceholder?: LocaleString;
    counterTemplate?: LocaleString;
    emailLabel?: LocaleString;
    submitLabel?: LocaleString;
    sendingLabel?: LocaleString;
    privacyLine?: LocaleString;
    thanks?: LocaleString;
    tooLong?: LocaleString;
    emptyText?: LocaleString;
    error?: LocaleString;
    sourceLabel?: LocaleString;
    sourceHref?: string;
  };
  view?: {
    date: string;
    when?: LocaleString;
    label?: LocaleString;
    paragraphs?: Array<{
      _key: string;
    } & LocaleText>;
  };
  service?: {
    label?: LocaleString;
    heading?: LocaleString;
    body?: LocaleText;
    ctaLabel?: LocaleString;
    service?: "zero-to-live" | "product-strategy" | "embedded-finance" | "expansion-gtm";
  };
};

export type LocaleString = {
  _type: "localeString";
  en?: string;
  tr?: string;
};

export type LocaleText = {
  _type: "localeText";
  en?: string;
  tr?: string;
};

export type Seo = {
  _type: "seo";
  title?: LocaleString;
  description?: LocaleText;
  ogImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  ogImageTr?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  noIndex?: boolean;
};

export type LocaleSlug = {
  _type: "localeSlug";
  en: Slug;
  tr: Slug;
};

export type SparkFormat = {
  _id: string;
  _type: "sparkFormat";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  number: number;
  name?: LocaleString;
  singularName?: LocaleString;
  slug?: LocaleSlug;
  status: "live" | "preparing";
  orderRank: number;
  seo?: Seo;
  description?: LocaleText;
  openLabel?: LocaleString;
  preparingLine?: LocaleString;
  comingLabel?: LocaleString;
  allIssuesLabel?: LocaleString;
  daysUnit?: LocaleString;
  line?: LocaleText;
  startLabel?: LocaleString;
  howLabel?: LocaleString;
  howHeading?: LocaleString;
  howSteps?: Array<{
    title?: LocaleString;
    body?: LocaleText;
    _type: "sparkHowStep";
    _key: string;
  }>;
  episodesLabel?: LocaleString;
  closeHeading?: LocaleString;
};

export type SparkSection = {
  _id: string;
  _type: "sparkSection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  seo?: Seo;
  bigWord?: LocaleString;
  heading?: LocaleString;
  tickerItems?: Array<{
    _key: string;
  } & LocaleString>;
  tickerTail?: LocaleString;
  formatsLabel?: LocaleString;
  readLabel?: LocaleString;
  backLabel?: LocaleString;
  sparkLabel?: LocaleString;
  launchDateLabel?: LocaleString;
  episode?: {
    yourPickTemplate?: LocaleString;
    roadTemplate?: LocaleString;
    otherRoadsLabel?: LocaleString;
    noteLabel?: LocaleString;
    dayTemplate?: LocaleString;
    nextTemplate?: LocaleString;
    footnoteTemplate?: LocaleString;
    sourceJoiner?: LocaleString;
  };
};

export type LegalPage = {
  _id: string;
  _type: "legalPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug: "terms" | "privacy" | "cookies" | "impressum";
  seo?: Seo;
  hero?: PageHero;
  blocks?: Array<{
    _key: string;
  } & LegalBlockDiv | {
    _key: string;
  } & LegalBlockHeading | {
    _key: string;
  } & LegalBlockSubheading | {
    _key: string;
  } & LegalBlockBold | {
    _key: string;
  } & LegalBlockField | {
    _key: string;
  } & LegalBlockList | {
    _key: string;
  } & LegalBlockTable>;
};

export type PageHero = {
  _type: "pageHero";
  eyebrow?: LocaleString;
  title?: LocaleString;
  intro?: LocaleText;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  seo?: Seo;
  backLabel?: LocaleString;
  label?: LocaleString;
  hero?: {
    headlineSentences?: Array<{
      _key: string;
    } & LocaleString>;
    cutWord?: LocaleString;
  };
  pair?: Array<{
    label?: LocaleString;
    lead?: LocaleText;
    body?: LocaleText;
    _type: "storyCard";
    _key: string;
  }>;
  result?: {
    label?: LocaleString;
    lead?: LocaleText;
    body?: LocaleText;
  };
  whyNine?: {
    label?: LocaleString;
    text?: LocaleText;
  };
  portraitAlt?: LocaleString;
  portrait?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type WorkPage = {
  _id: string;
  _type: "workPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  seo?: Seo;
  backLabel?: LocaleString;
  label?: LocaleString;
  heading?: LocaleString;
  lead?: LocaleText;
  readLabel?: LocaleString;
  caseLabel?: LocaleString;
  caseBackLabel?: LocaleString;
  sourcesLabel?: LocaleString;
  nextCaseLabel?: LocaleString;
};

export type ServicePage = {
  _id: string;
  _type: "servicePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug: string;
  order: number;
  name: LocaleString;
  shortLine?: LocaleText;
  audience?: LocaleString;
  slices?: Array<number>;
  seo?: Seo;
  opening?: {
    label?: LocaleString;
    heading?: LocaleString;
    intro?: LocaleText;
  };
  steps?: Array<{
    title?: LocaleString;
    line?: LocaleText;
    slices?: Array<number>;
    _type: "serviceStep";
    _key: string;
  }>;
  keep?: LocaleText;
};

export type ServicesPage = {
  _id: string;
  _type: "servicesPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  seo?: Seo;
  backLabel?: LocaleString;
  opening?: {
    label?: LocaleString;
    heading?: LocaleString;
    intro?: LocaleText;
  };
  servicePageLabels?: {
    backLabel?: LocaleString;
    stepsLabel?: LocaleString;
    otherServicesLabel?: LocaleString;
    keepLabel?: LocaleString;
    ctaLabel?: LocaleString;
  };
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  seo?: Seo;
  opening?: {
    eyebrowParts?: Array<{
      _key: string;
    } & LocaleString>;
    headlineSentences?: Array<{
      _key: string;
    } & LocaleString>;
    cutWord?: LocaleString;
    intro?: LocaleText;
    ctaLabel?: LocaleString;
    secondaryLinkLabel?: LocaleString;
    portraitAlt?: LocaleString;
    portrait?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
  startWhereYouAre?: {
    label?: LocaleString;
    heading?: LocaleString;
    text?: LocaleText;
    items?: Array<{
      title?: LocaleString;
      text?: LocaleText;
      _type: "titleText";
      _key: string;
    }>;
  };
  fourServices?: {
    label?: LocaleString;
    heading?: LocaleString;
    intro?: LocaleText;
  };
  work?: {
    label?: LocaleString;
    heading?: LocaleString;
    allLinkLabel?: LocaleString;
    featured?: {
      caseStudy?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "caseStudy";
      };
      label?: LocaleString;
      heading?: LocaleString;
      text?: LocaleText;
      figures?: Array<{
        value?: LocaleString;
        label?: LocaleString;
        _type: "figure";
        _key: string;
      }>;
      linkLabel?: LocaleString;
    };
    rows?: Array<{
      caseStudy?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "caseStudy";
      };
      line?: LocaleText;
      tags?: LocaleString;
      _type: "caseRow";
      _key: string;
    }>;
    alsoLabel?: LocaleString;
    also?: Array<{
      title?: LocaleString;
      text?: LocaleText;
      _type: "titleText";
      _key: string;
    }>;
  };
  withMe?: {
    label?: LocaleString;
    heading?: LocaleString;
    text?: LocaleText;
    points?: Array<{
      title?: LocaleString;
      text?: LocaleText;
      _type: "titleText";
      _key: string;
    }>;
    portraitAlt?: LocaleString;
    portrait?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
  spark?: {
    label?: LocaleString;
    heading?: LocaleString;
    text?: LocaleText;
    linkLabel?: LocaleString;
    cardLinkLabel?: LocaleString;
  };
};

export type CaseStudy = {
  _id: string;
  _type: "caseStudy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug: string;
  order?: number;
  name: LocaleString;
  subtitle?: LocaleText;
  market?: LocaleString;
  services?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "servicePage";
  }>;
  tags?: LocaleString;
  problem?: {
    label?: LocaleString;
    lead?: LocaleText;
    body?: LocaleText;
  };
  actions?: {
    label?: LocaleString;
    items?: Array<{
      _key: string;
    } & LocaleString>;
  };
  delivered?: {
    label?: LocaleString;
    lead?: LocaleText;
    body?: LocaleText;
  };
  figures?: Array<{
    value?: LocaleString;
    label?: LocaleString;
    _type: "figure";
    _key: string;
  }>;
  proof?: {
    value?: LocaleString;
    label?: LocaleString;
  };
  sources?: Array<string>;
  screens?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  seo?: Seo;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  brandName?: string;
  homeLabel?: LocaleString;
  servicesLabel?: LocaleString;
  nav?: Array<{
    label?: LocaleString;
    href?: "/work" | "/about" | "/spark" | "/impressum" | "/privacy" | "/cookies" | "/terms";
    _type: "navLink";
    _key: string;
  }>;
  servicesMenu?: {
    label?: LocaleString;
    heading?: LocaleString;
  };
  bookLabel?: LocaleString;
  menuLabel?: LocaleString;
  menuOpenLabel?: LocaleString;
  menuCloseLabel?: LocaleString;
  footer?: {
    email?: string;
    linkedinHref?: string;
    linkedinLabel?: string;
    legalLinks?: Array<{
      label?: LocaleString;
      href?: "/work" | "/about" | "/spark" | "/impressum" | "/privacy" | "/cookies" | "/terms";
      _type: "navLink";
      _key: string;
    }>;
    copyright?: string;
  };
  booking?: {
    calLink?: string;
    title?: LocaleString;
    meta?: LocaleString;
    closeLabel?: LocaleString;
    poweredBy?: LocaleString;
  };
  nextStep?: {
    label?: LocaleString;
    homeLabel?: LocaleString;
    headlineLead?: LocaleString;
    headlineCut?: LocaleString;
    steps?: Array<{
      _key: string;
    } & LocaleString>;
    ctaLabel?: LocaleString;
  };
  legal?: {
    backLabel?: LocaleString;
    tabsLabel?: LocaleString;
    tabs?: Array<{
      label?: LocaleString;
      href?: "/work" | "/about" | "/spark" | "/impressum" | "/privacy" | "/cookies" | "/terms";
      _type: "navLink";
      _key: string;
    }>;
  };
};

export type LegalBlockTable = {
  _type: "legalBlockTable";
  head?: {
    en?: Array<string>;
    tr?: Array<string>;
  };
  rows?: {
    en?: Array<{
      cells?: Array<string>;
      _type: "row";
      _key: string;
    }>;
    tr?: Array<{
      cells?: Array<string>;
      _type: "row";
      _key: string;
    }>;
  };
};

export type LegalBlockList = {
  _type: "legalBlockList";
  items?: {
    en?: Array<string>;
    tr?: Array<string>;
  };
};

export type LegalBlockField = {
  _type: "legalBlockField";
  label?: LocaleString;
  lines?: {
    en?: Array<string>;
    tr?: Array<string>;
  };
};

export type LegalBlockBold = {
  _type: "legalBlockBold";
  text?: LocaleText;
};

export type LegalBlockSubheading = {
  _type: "legalBlockSubheading";
  text?: LocaleString;
};

export type LegalBlockHeading = {
  _type: "legalBlockHeading";
  text?: LocaleString;
};

export type LegalBlockDiv = {
  _type: "legalBlockDiv";
  text?: LocaleText;
};

export type NoteHighlight = {
  _type: "noteHighlight";
  body: string;
};

export type StatHighlight = {
  _type: "statHighlight";
  figure: string;
  caption?: string;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = SparkRecordBlock | SparkChoiceDecision | SparkRulerTick | SparkChoiceOption | SparkSource | SparkFinalOption | SparkChapter | SparkDecision | SparkDecisionOption | SparkServiceTag | SparkStoryCard | SparkEpisode | LocaleString | LocaleText | Seo | LocaleSlug | SparkFormat | SparkSection | LegalPage | PageHero | AboutPage | WorkPage | ServicePage | ServicesPage | HomePage | CaseStudy | SanityImageCrop | SanityImageHotspot | SiteSettings | LegalBlockTable | LegalBlockList | LegalBlockField | LegalBlockBold | LegalBlockSubheading | LegalBlockHeading | LegalBlockDiv | NoteHighlight | StatHighlight | Slug | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/sanity/lib/content.ts
// Variable: SITE_CHROME_QUERY
// Query: {  "site": *[_type == "siteSettings" && _id == "siteSettings"][0]{    brandName, homeLabel, servicesLabel, nav, servicesMenu, bookLabel,    menuLabel, menuOpenLabel, menuCloseLabel, footer, booking, nextStep, legal  },  "services": *[_type == "servicePage"] | order(order asc){ slug, name, shortLine, audience, slices }}
export type SITE_CHROME_QUERYResult = {
  site: {
    brandName: string | null;
    homeLabel: LocaleString | null;
    servicesLabel: LocaleString | null;
    nav: Array<{
      label?: LocaleString;
      href?: "/about" | "/cookies" | "/impressum" | "/privacy" | "/spark" | "/terms" | "/work";
      _type: "navLink";
      _key: string;
    }> | null;
    servicesMenu: {
      label?: LocaleString;
      heading?: LocaleString;
    } | null;
    bookLabel: LocaleString | null;
    menuLabel: LocaleString | null;
    menuOpenLabel: LocaleString | null;
    menuCloseLabel: LocaleString | null;
    footer: {
      email?: string;
      linkedinHref?: string;
      linkedinLabel?: string;
      legalLinks?: Array<{
        label?: LocaleString;
        href?: "/about" | "/cookies" | "/impressum" | "/privacy" | "/spark" | "/terms" | "/work";
        _type: "navLink";
        _key: string;
      }>;
      copyright?: string;
    } | null;
    booking: {
      calLink?: string;
      title?: LocaleString;
      meta?: LocaleString;
      closeLabel?: LocaleString;
      poweredBy?: LocaleString;
    } | null;
    nextStep: {
      label?: LocaleString;
      homeLabel?: LocaleString;
      headlineLead?: LocaleString;
      headlineCut?: LocaleString;
      steps?: Array<{
        _key: string;
      } & LocaleString>;
      ctaLabel?: LocaleString;
    } | null;
    legal: {
      backLabel?: LocaleString;
      tabsLabel?: LocaleString;
      tabs?: Array<{
        label?: LocaleString;
        href?: "/about" | "/cookies" | "/impressum" | "/privacy" | "/spark" | "/terms" | "/work";
        _type: "navLink";
        _key: string;
      }>;
    } | null;
  } | null;
  services: Array<{
    slug: string;
    name: LocaleString;
    shortLine: LocaleText | null;
    audience: LocaleString | null;
    slices: Array<number> | null;
  }>;
};
// Variable: HOME_PAGE_QUERY
// Query: *[_type == "homePage" && _id == "homePage"][0]{  seo{ title, description },  opening{ ..., "portraitUrl": portrait.asset->url },  startWhereYouAre,  fourServices,  work{    label, heading, allLinkLabel, alsoLabel, also,    featured{      label, heading, text, figures, linkLabel,      "slug": caseStudy->slug,      "screens": caseStudy->screens[0...2]{ "src": asset->url, alt }    },    rows[]{ line, tags, "slug": caseStudy->slug, "name": caseStudy->name }  },  withMe{ ..., "portraitUrl": portrait.asset->url },  spark}
export type HOME_PAGE_QUERYResult = {
  seo: {
    title: LocaleString | null;
    description: LocaleText | null;
  } | null;
  opening: {
    eyebrowParts?: Array<{
      _key: string;
    } & LocaleString>;
    headlineSentences?: Array<{
      _key: string;
    } & LocaleString>;
    cutWord?: LocaleString;
    intro?: LocaleText;
    ctaLabel?: LocaleString;
    secondaryLinkLabel?: LocaleString;
    portraitAlt?: LocaleString;
    portrait?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    portraitUrl: string | null;
  } | null;
  startWhereYouAre: {
    label?: LocaleString;
    heading?: LocaleString;
    text?: LocaleText;
    items?: Array<{
      title?: LocaleString;
      text?: LocaleText;
      _type: "titleText";
      _key: string;
    }>;
  } | null;
  fourServices: {
    label?: LocaleString;
    heading?: LocaleString;
    intro?: LocaleText;
  } | null;
  work: {
    label: LocaleString | null;
    heading: LocaleString | null;
    allLinkLabel: LocaleString | null;
    alsoLabel: LocaleString | null;
    also: Array<{
      title?: LocaleString;
      text?: LocaleText;
      _type: "titleText";
      _key: string;
    }> | null;
    featured: {
      label: LocaleString | null;
      heading: LocaleString | null;
      text: LocaleText | null;
      figures: Array<{
        value?: LocaleString;
        label?: LocaleString;
        _type: "figure";
        _key: string;
      }> | null;
      linkLabel: LocaleString | null;
      slug: string | null;
      screens: Array<{
        src: string | null;
        alt: string | null;
      }> | null;
    } | null;
    rows: Array<{
      line: LocaleText | null;
      tags: LocaleString | null;
      slug: string | null;
      name: LocaleString | null;
    }> | null;
  } | null;
  withMe: {
    label?: LocaleString;
    heading?: LocaleString;
    text?: LocaleText;
    points?: Array<{
      title?: LocaleString;
      text?: LocaleText;
      _type: "titleText";
      _key: string;
    }>;
    portraitAlt?: LocaleString;
    portrait?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    portraitUrl: string | null;
  } | null;
  spark: {
    label?: LocaleString;
    heading?: LocaleString;
    text?: LocaleText;
    linkLabel?: LocaleString;
    cardLinkLabel?: LocaleString;
  } | null;
} | null;
// Variable: SPARK_CARDS_QUERY
// Query: *[_type == "sparkEpisode" && status in ["published", "coming"]]  | order(format->orderRank asc, number asc)[0...3]{    number, subject, hook, cardLine, publishedAt,    "status": select($preview && status in ["coming", "draft"] && previewLive == true => "published", status),    "episodeSlug": slug,    "format": format->{ name, singularName, slug, comingLabel }  }
export type SPARK_CARDS_QUERYResult = Array<{
  number: number;
  subject: LocaleString | null;
  hook: LocaleText | null;
  cardLine: LocaleText | null;
  publishedAt: string | null;
  status: "coming" | "draft" | "published";
  episodeSlug: LocaleSlug | null;
  format: {
    name: LocaleString | null;
    singularName: LocaleString | null;
    slug: LocaleSlug | null;
    comingLabel: LocaleString | null;
  };
}>;
// Variable: SERVICES_PAGE_QUERY
// Query: *[_type == "servicesPage" && _id == "servicesPage"][0]{  seo{ title, description }, backLabel, opening, servicePageLabels}
export type SERVICES_PAGE_QUERYResult = {
  seo: {
    title: LocaleString | null;
    description: LocaleText | null;
  } | null;
  backLabel: LocaleString | null;
  opening: {
    label?: LocaleString;
    heading?: LocaleString;
    intro?: LocaleText;
  } | null;
  servicePageLabels: {
    backLabel?: LocaleString;
    stepsLabel?: LocaleString;
    otherServicesLabel?: LocaleString;
    keepLabel?: LocaleString;
    ctaLabel?: LocaleString;
  } | null;
} | null;
// Variable: SERVICE_PAGES_QUERY
// Query: *[_type == "servicePage"] | order(order asc){  slug, seo{ title, description }, opening, steps[]{ title, line, slices }, keep}
export type SERVICE_PAGES_QUERYResult = Array<{
  slug: string;
  seo: {
    title: LocaleString | null;
    description: LocaleText | null;
  } | null;
  opening: {
    label?: LocaleString;
    heading?: LocaleString;
    intro?: LocaleText;
  } | null;
  steps: Array<{
    title: LocaleString | null;
    line: LocaleText | null;
    slices: Array<number> | null;
  }> | null;
  keep: LocaleText | null;
}>;
// Variable: WORK_PAGE_QUERY
// Query: *[_type == "workPage" && _id == "workPage"][0]{  seo{ title, description }, backLabel, label, heading, lead, readLabel,  caseLabel, caseBackLabel, sourcesLabel, nextCaseLabel}
export type WORK_PAGE_QUERYResult = {
  seo: {
    title: LocaleString | null;
    description: LocaleText | null;
  } | null;
  backLabel: LocaleString | null;
  label: LocaleString | null;
  heading: LocaleString | null;
  lead: LocaleText | null;
  readLabel: LocaleString | null;
  caseLabel: LocaleString | null;
  caseBackLabel: LocaleString | null;
  sourcesLabel: LocaleString | null;
  nextCaseLabel: LocaleString | null;
} | null;
// Variable: CASES_QUERY
// Query: *[_type == "caseStudy"] | order(order asc){  slug, seo{ title, description }, name, subtitle, market, tags,  "publishedAt": _createdAt, "modifiedAt": _updatedAt,  "services": services[]->slug,  problem, actions, delivered, figures, proof, sources,  "screens": screens[0...2]{ "url": asset->url, alt, "width": asset->metadata.dimensions.width, "height": asset->metadata.dimensions.height }}
export type CASES_QUERYResult = Array<{
  slug: string;
  seo: {
    title: LocaleString | null;
    description: LocaleText | null;
  } | null;
  name: LocaleString;
  subtitle: LocaleText | null;
  market: LocaleString | null;
  tags: LocaleString | null;
  publishedAt: string;
  modifiedAt: string;
  services: Array<string> | null;
  problem: {
    label?: LocaleString;
    lead?: LocaleText;
    body?: LocaleText;
  } | null;
  actions: {
    label?: LocaleString;
    items?: Array<{
      _key: string;
    } & LocaleString>;
  } | null;
  delivered: {
    label?: LocaleString;
    lead?: LocaleText;
    body?: LocaleText;
  } | null;
  figures: Array<{
    value?: LocaleString;
    label?: LocaleString;
    _type: "figure";
    _key: string;
  }> | null;
  proof: {
    value?: LocaleString;
    label?: LocaleString;
  } | null;
  sources: Array<string> | null;
  screens: Array<{
    url: string | null;
    alt: string | null;
    width: number | null;
    height: number | null;
  }> | null;
}>;
// Variable: ABOUT_PAGE_QUERY
// Query: *[_type == "aboutPage" && _id == "aboutPage"][0]{  seo{ title, description }, backLabel, label, hero, pair, result, whyNine, portraitAlt,  "portraitUrl": portrait.asset->url}
export type ABOUT_PAGE_QUERYResult = {
  seo: {
    title: LocaleString | null;
    description: LocaleText | null;
  } | null;
  backLabel: LocaleString | null;
  label: LocaleString | null;
  hero: {
    headlineSentences?: Array<{
      _key: string;
    } & LocaleString>;
    cutWord?: LocaleString;
  } | null;
  pair: Array<{
    label?: LocaleString;
    lead?: LocaleText;
    body?: LocaleText;
    _type: "storyCard";
    _key: string;
  }> | null;
  result: {
    label?: LocaleString;
    lead?: LocaleText;
    body?: LocaleText;
  } | null;
  whyNine: {
    label?: LocaleString;
    text?: LocaleText;
  } | null;
  portraitAlt: LocaleString | null;
  portraitUrl: string | null;
} | null;
// Variable: SPARK_HUB_QUERY
// Query: {  "section": *[_type == "sparkSection" && _id == "sparkSection"][0]{    seo{ title, description }, bigWord, heading, tickerItems, tickerTail, readLabel,    backLabel, sparkLabel, formatsLabel, launchDateLabel,    episode{ yourPickTemplate, roadTemplate, otherRoadsLabel, noteLabel, dayTemplate, nextTemplate, footnoteTemplate, sourceJoiner }  },  "formats": *[_type == "sparkFormat"] | order(orderRank asc){    number, name, slug, status, seo{ title, description }, description, openLabel, preparingLine,    comingLabel, allIssuesLabel, daysUnit, line, startLabel, howLabel, howHeading,    "howSteps": coalesce(howSteps[]{ title, body }, []), episodesLabel, closeHeading,    "coming": *[_type == "sparkEpisode" && references(^._id) && status == "coming"      && !($preview && previewLive == true)] | order(number asc){      number, subject, hook    }  }}
export type SPARK_HUB_QUERYResult = {
  section: {
    seo: {
      title: LocaleString | null;
      description: LocaleText | null;
    } | null;
    bigWord: LocaleString | null;
    heading: LocaleString | null;
    tickerItems: Array<{
      _key: string;
    } & LocaleString> | null;
    tickerTail: LocaleString | null;
    readLabel: LocaleString | null;
    backLabel: LocaleString | null;
    sparkLabel: LocaleString | null;
    formatsLabel: LocaleString | null;
    launchDateLabel: LocaleString | null;
    episode: {
      yourPickTemplate: LocaleString | null;
      roadTemplate: LocaleString | null;
      otherRoadsLabel: LocaleString | null;
      noteLabel: LocaleString | null;
      dayTemplate: LocaleString | null;
      nextTemplate: LocaleString | null;
      footnoteTemplate: LocaleString | null;
      sourceJoiner: LocaleString | null;
    } | null;
  } | null;
  formats: Array<{
    number: number;
    name: LocaleString | null;
    slug: LocaleSlug | null;
    status: "live" | "preparing";
    seo: {
      title: LocaleString | null;
      description: LocaleText | null;
    } | null;
    description: LocaleText | null;
    openLabel: LocaleString | null;
    preparingLine: LocaleString | null;
    comingLabel: LocaleString | null;
    allIssuesLabel: LocaleString | null;
    daysUnit: LocaleString | null;
    line: LocaleText | null;
    startLabel: LocaleString | null;
    howLabel: LocaleString | null;
    howHeading: LocaleString | null;
    howSteps: Array<{
      title: LocaleString | null;
      body: LocaleText | null;
    }> | Array<never>;
    episodesLabel: LocaleString | null;
    closeHeading: LocaleString | null;
    coming: Array<{
      number: number;
      subject: LocaleString | null;
      hook: LocaleText | null;
    }>;
  }>;
};
// Variable: SPARK_EPISODES_QUERY
// Query: *[_type == "sparkEpisode"  && (status == "published" || ($preview && status in ["coming", "draft"] && previewLive == true))  && defined(slug.en.current) && defined(slug.tr.current)] | order(number asc){    number, subject, hook, seo{ title, description }, publishedAt, lastCheckedAt, _updatedAt, layout,    launchDate, closureDate, durationLabel,    "slug": slug, "formatSlug": format->slug,    hero, dayClock, interlude, lastDay, finalQuestion, next, sourcesLabel, correctionLine, closeHeading,    "note": note{ label, "paragraphs": coalesce(paragraphs, []) },    "chapters": coalesce(chapters[]{ id, label, title, lead, "paragraphs": coalesce(paragraphs, []), card, decision }, []),    "lessons": coalesce(lessons[]{ heading, body }, []),    "sources": coalesce(sources[]{ n, "links": coalesce(links[]{ label, href }, []) }, []),    opening, standfirst, provenance, clock, intro, labels, view, service,    "ruler": ruler{ after, "ticks": coalesce(ticks[]{ date, label, caption }, []) },    "decisions": coalesce(decisions[]{      date, when, label, title, record,      "paragraphs": coalesce(paragraphs, []), "reveal": coalesce(reveal, []),      "options": coalesce(options[]{ key, text }, []),      "sources": coalesce(sources[]{ label, href }, [])    }, []),    "records": coalesce(records[]{      date, when, label, "paragraphs": coalesce(paragraphs, []), "sources": coalesce(sources[]{ label, href }, [])    }, []),    "twist": twist{      ..., "paragraphs": coalesce(paragraphs, []), "options": coalesce(options[]{ key, text }, [])    }  }
export type SPARK_EPISODES_QUERYResult = Array<{
  number: number;
  subject: LocaleString | null;
  hook: LocaleText | null;
  seo: {
    title: LocaleString | null;
    description: LocaleText | null;
  } | null;
  publishedAt: string | null;
  lastCheckedAt: string | null;
  _updatedAt: string;
  layout: "decisions" | "story" | null;
  launchDate: string | null;
  closureDate: string | null;
  durationLabel: LocaleString | null;
  slug: LocaleSlug | null;
  formatSlug: LocaleSlug | null;
  hero: {
    label?: LocaleString;
    title?: LocaleText;
    sub?: LocaleText;
    invite?: LocaleText;
    startLabel?: LocaleString;
    cardDay?: string;
    cardState?: LocaleString;
    figure?: string;
    figureLabel?: LocaleString;
  } | null;
  dayClock: {
    label?: LocaleString;
    ofLabel?: LocaleString;
  } | null;
  interlude: {
    afterChapter?: string;
    text?: LocaleText;
    card?: SparkStoryCard;
  } | null;
  lastDay: {
    label?: LocaleString;
    text?: LocaleText;
  } | null;
  finalQuestion: {
    label?: LocaleString;
    title?: LocaleText;
    lead?: LocaleText;
    ctaLabel?: LocaleString;
    options?: Array<{
      _key: string;
    } & SparkFinalOption>;
  } | null;
  next: {
    number?: string;
    name?: LocaleString;
    line?: LocaleText;
  } | null;
  sourcesLabel: LocaleString | null;
  correctionLine: LocaleText | null;
  closeHeading: LocaleString | null;
  note: {
    label: LocaleString | null;
    paragraphs: Array<{
      _key: string;
    } & LocaleText> | Array<never>;
  } | null;
  chapters: Array<{
    id: string;
    label: LocaleString | null;
    title: LocaleString | null;
    lead: LocaleText | null;
    paragraphs: Array<{
      _key: string;
    } & LocaleText> | Array<never>;
    card: SparkStoryCard | null;
    decision: SparkDecision | null;
  }> | Array<never>;
  lessons: Array<{
    heading: LocaleString | null;
    body: LocaleText | null;
  }> | Array<never>;
  sources: Array<{
    n: number;
    links: Array<{
      label: LocaleString | null;
      href: string | null;
    }> | Array<never>;
  }> | Array<never>;
  opening: {
    label?: LocaleString;
    meta?: LocaleString;
    figure?: string;
    figureLabel?: LocaleString;
  } | null;
  standfirst: LocaleText | null;
  provenance: LocaleString | null;
  clock: {
    rangeLabel?: LocaleString;
    start: string;
    end: string;
  } | null;
  intro: LocaleText | null;
  labels: {
    ask?: LocaleString;
    skip?: LocaleString;
    match?: LocaleString;
    noMatch?: LocaleString;
    revealLabel?: LocaleString;
    sourcesLabel?: LocaleString;
  } | null;
  view: {
    date: string;
    when?: LocaleString;
    label?: LocaleString;
    paragraphs?: Array<{
      _key: string;
    } & LocaleText>;
  } | null;
  service: {
    label?: LocaleString;
    heading?: LocaleString;
    body?: LocaleText;
    ctaLabel?: LocaleString;
    service?: "embedded-finance" | "expansion-gtm" | "product-strategy" | "zero-to-live";
  } | null;
  ruler: {
    after: LocaleText | null;
    ticks: Array<{
      date: string;
      label: LocaleString | null;
      caption: LocaleString | null;
    }> | Array<never>;
  } | null;
  decisions: Array<{
    date: string;
    when: LocaleString | null;
    label: LocaleString | null;
    title: LocaleString | null;
    record: string;
    paragraphs: Array<{
      _key: string;
    } & LocaleText> | Array<never>;
    reveal: Array<{
      _key: string;
    } & LocaleText> | Array<never>;
    options: Array<{
      key: string;
      text: LocaleText | null;
    }> | Array<never>;
    sources: Array<{
      label: LocaleString | null;
      href: string | null;
    }> | Array<never>;
  }> | Array<never>;
  records: Array<{
    date: string;
    when: LocaleString | null;
    label: LocaleString | null;
    paragraphs: Array<{
      _key: string;
    } & LocaleText> | Array<never>;
    sources: Array<{
      label: LocaleString | null;
      href: string | null;
    }> | Array<never>;
  }> | Array<never>;
  twist: {
    date: string;
    when?: LocaleString;
    label?: LocaleString;
    paragraphs: Array<{
      _key: string;
    } & LocaleText> | Array<never>;
    question?: LocaleText;
    options: Array<{
      key: string;
      text: LocaleText | null;
    }> | Array<never>;
    freeKey?: string;
    freeLabel?: LocaleString;
    freePlaceholder?: LocaleString;
    counterTemplate?: LocaleString;
    emailLabel?: LocaleString;
    submitLabel?: LocaleString;
    sendingLabel?: LocaleString;
    privacyLine?: LocaleString;
    thanks?: LocaleString;
    tooLong?: LocaleString;
    emptyText?: LocaleString;
    error?: LocaleString;
    sourceLabel?: LocaleString;
    sourceHref?: string;
  } | null;
}>;

// Source: ./src/sanity/lib/queries.ts
// Variable: LEGAL_PAGE_QUERY
// Query: *[_type == "legalPage" && slug == $slug][0]{    "hero": hero{      "eyebrow": select($locale == "tr" => coalesce(eyebrow.tr, eyebrow.en), eyebrow.en),      "title": select($locale == "tr" => coalesce(title.tr, title.en), title.en),      "intro": select($locale == "tr" => coalesce(intro.tr, intro.en), intro.en)    },    "blocks": blocks[]{      _type,      "text": select($locale == "tr" => coalesce(text.tr, text.en), text.en),      "label": select($locale == "tr" => coalesce(label.tr, label.en), label.en),      "lines": select($locale == "tr" => coalesce(lines.tr, lines.en), lines.en),      "items": select($locale == "tr" => coalesce(items.tr, items.en), items.en),      "head": select($locale == "tr" => coalesce(head.tr, head.en), head.en),      "rows": select($locale == "tr" => coalesce(rows.tr, rows.en), rows.en)    }  }
export type LEGAL_PAGE_QUERYResult = {
  hero: {
    eyebrow: string | null;
    title: string | null;
    intro: string | null;
  } | null;
  blocks: Array<{
    _type: "legalBlockBold";
    text: string | null;
    label: null;
    lines: null;
    items: null;
    head: null;
    rows: null;
  } | {
    _type: "legalBlockDiv";
    text: string | null;
    label: null;
    lines: null;
    items: null;
    head: null;
    rows: null;
  } | {
    _type: "legalBlockField";
    text: null;
    label: string | null;
    lines: Array<string> | null;
    items: null;
    head: null;
    rows: null;
  } | {
    _type: "legalBlockHeading";
    text: string | null;
    label: null;
    lines: null;
    items: null;
    head: null;
    rows: null;
  } | {
    _type: "legalBlockList";
    text: null;
    label: null;
    lines: null;
    items: Array<string> | null;
    head: null;
    rows: null;
  } | {
    _type: "legalBlockSubheading";
    text: string | null;
    label: null;
    lines: null;
    items: null;
    head: null;
    rows: null;
  } | {
    _type: "legalBlockTable";
    text: null;
    label: null;
    lines: null;
    items: null;
    head: Array<string> | null;
    rows: Array<{
      cells?: Array<string>;
      _type: "row";
      _key: string;
    }> | null;
  }> | null;
} | null;
// Variable: SITE_SEO_QUERY
// Query: *[_type == "siteSettings"][0].seo{    "title": select($locale == "tr" => coalesce(title.tr, title.en), title.en),    "description": select($locale == "tr" => coalesce(description.tr, description.en), description.en),    "ogImage": select($locale == "tr" && defined(ogImageTr.asset) => ogImageTr, ogImage){      "url": asset->url,      "alt": coalesce(alt, ""),      "width": asset->metadata.dimensions.width,      "height": asset->metadata.dimensions.height,      "lqip": asset->metadata.lqip    },    noIndex  }
export type SITE_SEO_QUERYResult = {
  title: string | null;
  description: string | null;
  ogImage: {
    url: string | null;
    alt: string | "";
    width: number | null;
    height: number | null;
    lqip: string | null;
  } | null;
  noIndex: boolean | null;
} | null;
// Variable: LEGAL_PAGE_SEO_QUERY
// Query: *[_type == "legalPage" && slug == $slug][0].seo{    "title": select($locale == "tr" => coalesce(title.tr, title.en), title.en),    "description": select($locale == "tr" => coalesce(description.tr, description.en), description.en),    "ogImage": ogImage{      "url": asset->url,      "alt": coalesce(alt, ""),      "width": asset->metadata.dimensions.width,      "height": asset->metadata.dimensions.height,      "lqip": asset->metadata.lqip    },    noIndex  }
export type LEGAL_PAGE_SEO_QUERYResult = {
  title: string | null;
  description: string | null;
  ogImage: {
    url: string | null;
    alt: string | "";
    width: number | null;
    height: number | null;
    lqip: string | null;
  } | null;
  noIndex: boolean | null;
} | null;
// Variable: SITE_LOGO_QUERY
// Query: *[_type == "siteSettings"][0].logo{    "url": asset->url,    "alt": coalesce(alt, ""),    "width": asset->metadata.dimensions.width,    "height": asset->metadata.dimensions.height,    "lqip": asset->metadata.lqip  }
export type SITE_LOGO_QUERYResult = {
  url: string | null;
  alt: string | "";
  width: number | null;
  height: number | null;
  lqip: string | null;
} | null;
// Variable: SPARK_FORMAT_QUERY
// Query: *[_type == "sparkFormat" && select($locale == "tr" => slug.tr.current, slug.en.current) == $formatSlug][0]{    "altFormatSlug": select($locale == "tr" => slug.en.current, slug.tr.current),    "episodes": *[_type == "sparkEpisode" && references(^._id)      && (status == "published" || ($preview && status in ["coming", "draft"] && previewLive == true))] | order(number asc){      number,      "subject": select($locale == "tr" => coalesce(subject.tr, subject.en), subject.en),      country,      launchDate,      closureDate,      publishedAt,      "hook": select($locale == "tr" => coalesce(hook.tr, hook.en), hook.en),      "durationLabel": select($locale == "tr" => coalesce(durationLabel.tr, durationLabel.en), durationLabel.en),      "slug": select($locale == "tr" => slug.tr.current, slug.en.current)    }  }
export type SPARK_FORMAT_QUERYResult = {
  altFormatSlug: string | null;
  episodes: Array<{
    number: number;
    subject: string | null;
    country: string | null;
    launchDate: string | null;
    closureDate: string | null;
    publishedAt: string | null;
    hook: string | null;
    durationLabel: string | null;
    slug: string | null;
  }>;
} | null;
// Variable: SPARK_EPISODE_SLUGS_QUERY
// Query: *[_type == "sparkEpisode" && defined(slug.en.current) && defined(slug.tr.current)]{    "episodeEn": slug.en.current,    "episodeTr": slug.tr.current,    "formatEn": format->slug.en.current,    "formatTr": format->slug.tr.current,    "status": select($preview && status in ["coming", "draft"] && previewLive == true => "published", status),    lastCheckedAt,    _updatedAt  }
export type SPARK_EPISODE_SLUGS_QUERYResult = Array<{
  episodeEn: string;
  episodeTr: string;
  formatEn: string | null;
  formatTr: string | null;
  status: "coming" | "draft" | "published";
  lastCheckedAt: string | null;
  _updatedAt: string;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "{\n  \"site\": *[_type == \"siteSettings\" && _id == \"siteSettings\"][0]{\n    brandName, homeLabel, servicesLabel, nav, servicesMenu, bookLabel,\n    menuLabel, menuOpenLabel, menuCloseLabel, footer, booking, nextStep, legal\n  },\n  \"services\": *[_type == \"servicePage\"] | order(order asc){ slug, name, shortLine, audience, slices }\n}": SITE_CHROME_QUERYResult;
    "*[_type == \"homePage\" && _id == \"homePage\"][0]{\n  seo{ title, description },\n  opening{ ..., \"portraitUrl\": portrait.asset->url },\n  startWhereYouAre,\n  fourServices,\n  work{\n    label, heading, allLinkLabel, alsoLabel, also,\n    featured{\n      label, heading, text, figures, linkLabel,\n      \"slug\": caseStudy->slug,\n      \"screens\": caseStudy->screens[0...2]{ \"src\": asset->url, alt }\n    },\n    rows[]{ line, tags, \"slug\": caseStudy->slug, \"name\": caseStudy->name }\n  },\n  withMe{ ..., \"portraitUrl\": portrait.asset->url },\n  spark\n}": HOME_PAGE_QUERYResult;
    "*[_type == \"sparkEpisode\" && status in [\"published\", \"coming\"]]\n  | order(format->orderRank asc, number asc)[0...3]{\n    number, subject, hook, cardLine, publishedAt,\n    \"status\": select($preview && status in [\"coming\", \"draft\"] && previewLive == true => \"published\", status),\n    \"episodeSlug\": slug,\n    \"format\": format->{ name, singularName, slug, comingLabel }\n  }": SPARK_CARDS_QUERYResult;
    "*[_type == \"servicesPage\" && _id == \"servicesPage\"][0]{\n  seo{ title, description }, backLabel, opening, servicePageLabels\n}": SERVICES_PAGE_QUERYResult;
    "*[_type == \"servicePage\"] | order(order asc){\n  slug, seo{ title, description }, opening, steps[]{ title, line, slices }, keep\n}": SERVICE_PAGES_QUERYResult;
    "*[_type == \"workPage\" && _id == \"workPage\"][0]{\n  seo{ title, description }, backLabel, label, heading, lead, readLabel,\n  caseLabel, caseBackLabel, sourcesLabel, nextCaseLabel\n}": WORK_PAGE_QUERYResult;
    "*[_type == \"caseStudy\"] | order(order asc){\n  slug, seo{ title, description }, name, subtitle, market, tags,\n  \"publishedAt\": _createdAt, \"modifiedAt\": _updatedAt,\n  \"services\": services[]->slug,\n  problem, actions, delivered, figures, proof, sources,\n  \"screens\": screens[0...2]{ \"url\": asset->url, alt, \"width\": asset->metadata.dimensions.width, \"height\": asset->metadata.dimensions.height }\n}": CASES_QUERYResult;
    "*[_type == \"aboutPage\" && _id == \"aboutPage\"][0]{\n  seo{ title, description }, backLabel, label, hero, pair, result, whyNine, portraitAlt,\n  \"portraitUrl\": portrait.asset->url\n}": ABOUT_PAGE_QUERYResult;
    "{\n  \"section\": *[_type == \"sparkSection\" && _id == \"sparkSection\"][0]{\n    seo{ title, description }, bigWord, heading, tickerItems, tickerTail, readLabel,\n    backLabel, sparkLabel, formatsLabel, launchDateLabel,\n    episode{ yourPickTemplate, roadTemplate, otherRoadsLabel, noteLabel, dayTemplate, nextTemplate, footnoteTemplate, sourceJoiner }\n  },\n  \"formats\": *[_type == \"sparkFormat\"] | order(orderRank asc){\n    number, name, slug, status, seo{ title, description }, description, openLabel, preparingLine,\n    comingLabel, allIssuesLabel, daysUnit, line, startLabel, howLabel, howHeading,\n    \"howSteps\": coalesce(howSteps[]{ title, body }, []), episodesLabel, closeHeading,\n    \"coming\": *[_type == \"sparkEpisode\" && references(^._id) && status == \"coming\"\n      && !($preview && previewLive == true)] | order(number asc){\n      number, subject, hook\n    }\n  }\n}": SPARK_HUB_QUERYResult;
    "*[_type == \"sparkEpisode\"\n  && (status == \"published\" || ($preview && status in [\"coming\", \"draft\"] && previewLive == true))\n  && defined(slug.en.current) && defined(slug.tr.current)] | order(number asc){\n    number, subject, hook, seo{ title, description }, publishedAt, lastCheckedAt, _updatedAt, layout,\n    launchDate, closureDate, durationLabel,\n    \"slug\": slug, \"formatSlug\": format->slug,\n    hero, dayClock, interlude, lastDay, finalQuestion, next, sourcesLabel, correctionLine, closeHeading,\n    \"note\": note{ label, \"paragraphs\": coalesce(paragraphs, []) },\n    \"chapters\": coalesce(chapters[]{ id, label, title, lead, \"paragraphs\": coalesce(paragraphs, []), card, decision }, []),\n    \"lessons\": coalesce(lessons[]{ heading, body }, []),\n    \"sources\": coalesce(sources[]{ n, \"links\": coalesce(links[]{ label, href }, []) }, []),\n    opening, standfirst, provenance, clock, intro, labels, view, service,\n    \"ruler\": ruler{ after, \"ticks\": coalesce(ticks[]{ date, label, caption }, []) },\n    \"decisions\": coalesce(decisions[]{\n      date, when, label, title, record,\n      \"paragraphs\": coalesce(paragraphs, []), \"reveal\": coalesce(reveal, []),\n      \"options\": coalesce(options[]{ key, text }, []),\n      \"sources\": coalesce(sources[]{ label, href }, [])\n    }, []),\n    \"records\": coalesce(records[]{\n      date, when, label, \"paragraphs\": coalesce(paragraphs, []), \"sources\": coalesce(sources[]{ label, href }, [])\n    }, []),\n    \"twist\": twist{\n      ..., \"paragraphs\": coalesce(paragraphs, []), \"options\": coalesce(options[]{ key, text }, [])\n    }\n  }": SPARK_EPISODES_QUERYResult;
    "\n  *[_type == \"legalPage\" && slug == $slug][0]{\n    \"hero\": hero{\n      \"eyebrow\": select($locale == \"tr\" => coalesce(eyebrow.tr, eyebrow.en), eyebrow.en),\n      \"title\": select($locale == \"tr\" => coalesce(title.tr, title.en), title.en),\n      \"intro\": select($locale == \"tr\" => coalesce(intro.tr, intro.en), intro.en)\n    },\n    \"blocks\": blocks[]{\n      _type,\n      \"text\": select($locale == \"tr\" => coalesce(text.tr, text.en), text.en),\n      \"label\": select($locale == \"tr\" => coalesce(label.tr, label.en), label.en),\n      \"lines\": select($locale == \"tr\" => coalesce(lines.tr, lines.en), lines.en),\n      \"items\": select($locale == \"tr\" => coalesce(items.tr, items.en), items.en),\n      \"head\": select($locale == \"tr\" => coalesce(head.tr, head.en), head.en),\n      \"rows\": select($locale == \"tr\" => coalesce(rows.tr, rows.en), rows.en)\n    }\n  }\n": LEGAL_PAGE_QUERYResult;
    "\n  *[_type == \"siteSettings\"][0].seo{\n    \"title\": select($locale == \"tr\" => coalesce(title.tr, title.en), title.en),\n    \"description\": select($locale == \"tr\" => coalesce(description.tr, description.en), description.en),\n    \"ogImage\": select($locale == \"tr\" && defined(ogImageTr.asset) => ogImageTr, ogImage){\n      \"url\": asset->url,\n      \"alt\": coalesce(alt, \"\"),\n      \"width\": asset->metadata.dimensions.width,\n      \"height\": asset->metadata.dimensions.height,\n      \"lqip\": asset->metadata.lqip\n    },\n    noIndex\n  }\n": SITE_SEO_QUERYResult;
    "\n  *[_type == \"legalPage\" && slug == $slug][0].seo{\n    \"title\": select($locale == \"tr\" => coalesce(title.tr, title.en), title.en),\n    \"description\": select($locale == \"tr\" => coalesce(description.tr, description.en), description.en),\n    \"ogImage\": ogImage{\n      \"url\": asset->url,\n      \"alt\": coalesce(alt, \"\"),\n      \"width\": asset->metadata.dimensions.width,\n      \"height\": asset->metadata.dimensions.height,\n      \"lqip\": asset->metadata.lqip\n    },\n    noIndex\n  }\n": LEGAL_PAGE_SEO_QUERYResult;
    "\n  *[_type == \"siteSettings\"][0].logo{\n    \"url\": asset->url,\n    \"alt\": coalesce(alt, \"\"),\n    \"width\": asset->metadata.dimensions.width,\n    \"height\": asset->metadata.dimensions.height,\n    \"lqip\": asset->metadata.lqip\n  }\n": SITE_LOGO_QUERYResult;
    "\n  *[_type == \"sparkFormat\" && select($locale == \"tr\" => slug.tr.current, slug.en.current) == $formatSlug][0]{\n    \"altFormatSlug\": select($locale == \"tr\" => slug.en.current, slug.tr.current),\n    \"episodes\": *[_type == \"sparkEpisode\" && references(^._id)\n      && (status == \"published\" || ($preview && status in [\"coming\", \"draft\"] && previewLive == true))] | order(number asc){\n      number,\n      \"subject\": select($locale == \"tr\" => coalesce(subject.tr, subject.en), subject.en),\n      country,\n      launchDate,\n      closureDate,\n      publishedAt,\n      \"hook\": select($locale == \"tr\" => coalesce(hook.tr, hook.en), hook.en),\n      \"durationLabel\": select($locale == \"tr\" => coalesce(durationLabel.tr, durationLabel.en), durationLabel.en),\n      \"slug\": select($locale == \"tr\" => slug.tr.current, slug.en.current)\n    }\n  }\n": SPARK_FORMAT_QUERYResult;
    "\n  *[_type == \"sparkEpisode\" && defined(slug.en.current) && defined(slug.tr.current)]{\n    \"episodeEn\": slug.en.current,\n    \"episodeTr\": slug.tr.current,\n    \"formatEn\": format->slug.en.current,\n    \"formatTr\": format->slug.tr.current,\n    \"status\": select($preview && status in [\"coming\", \"draft\"] && previewLive == true => \"published\", status),\n    lastCheckedAt,\n    _updatedAt\n  }\n": SPARK_EPISODE_SLUGS_QUERYResult;
  }
}
